name: "Staging: Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.11.1'

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: 'eu-central-1'

#        @TODO - comment in after backend is created
#      - name: 'Backend: Install NPM Dependencies'
#        run: cd backend && npm install
#
#      - name: 'Backend: Build'
#        run: cd backend && npm run build
#
#      - name: 'Backend: Remove Development Dependencies'
#        run: cd backend && npm prune --production

      - name: 'Frontend: Install NPM Dependencies'
        run: npm ci

      - name: 'Frontend: Build'
        run: npm run client:build

      - name: 'Frontend: Remove Development Dependencies'
        run: npm prune:frontend

#        @TODO - comment in after infa is created
#      - name: 'Infrastructure: Install NPM Dependencies'
#        run: cd infrastructure && npm install
#
#      - name: 'Infrastructure: Bootstrap AWS CDK'
#        run: cd infrastructure && npm run bootstrap:hamiti
#
#      - name: 'Infrastructure: Deploy Hamiti Stack'
#        run: cd infrastructure && npm run deploy:hamiti
